// Canonical seed content for the Themis backend. The Reyes matter is fully
// populated (documents, chronology, entities, chat) so search/chat/privilege
// behave realistically; the other matters are lighter, matching their status.

import type {
  CaseTheory,
  ChronEvent,
  DocItem,
  Entity,
  GapFinding,
  IngestStage,
  MatterStatus,
} from "./types.js";

export interface SeedMatter {
  id: string;
  name: string;
  client: string;
  matterType: string;
  leadAttorney: string;
  status: MatterStatus;
  pages: number;
  docs: number;
  ingestPercent: number;
  lastActivity: string;
  caseTheory: CaseTheory;
  ingestStages: IngestStage[];
  gapFindings: GapFinding[];
}

export type SeedDoc = Omit<DocItem, "pages"> & { pages?: number; sortOrder: number };

const reyesIngest: IngestStage[] = [
  { label: "Upload", done: true },
  { label: "OCR (Azure DI)", done: true },
  { label: "Bates stamp", done: true },
  { label: "Dedup + threading", done: true },
  { label: "Extraction", done: true },
  { label: "Privilege scan", done: true },
];

export const matters: SeedMatter[] = [
  {
    id: "mata-avianca",
    name: "Mata v. Avianca, Inc.",
    client: "Roberto Mata",
    matterType: "Personal Injury — International Air Carrier (Montreal Convention)",
    leadAttorney: "P. LoDuca / S. Schwartz",
    status: "In Review",
    pages: 1842,
    docs: 47,
    ingestPercent: 100,
    lastActivity: "1 day ago",
    caseTheory: {
      posture:
        "Plaintiff Roberto Mata alleges injury from a metal serving cart on Avianca Flight 670 (Aug 27, 2019). Defendant moved to dismiss as time-barred under the Montreal Convention's two-year limitations period. Plaintiff's opposition cited six judicial decisions that did not exist — ChatGPT fabrications. Judge Castel imposed Rule 11 sanctions and dismissed the underlying claim as time-barred.",
      claims: [
        "Personal injury under Montreal Convention Article 17",
        "Tolling of Article 35 two-year SoL during Avianca's Chapter 11 stay (failed)",
      ],
      defenses: [
        "Time-barred under Montreal Convention Article 35",
        "Article 35 is a condition precedent — no equitable tolling",
      ],
      keyDates: [
        { label: "Flight 670 incident", date: "2019-08-27" },
        { label: "Complaint filed (NY Sup. Ct.)", date: "2022-02-02" },
        { label: "Removed to S.D.N.Y.", date: "2022-02-22" },
        { label: "Motion to Dismiss filed", date: "2023-01-13" },
        { label: "Affirmation with 6 fabricated cites", date: "2023-03-01" },
        { label: "Sanctions order ($5,000)", date: "2023-06-22" },
      ],
    },
    ingestStages: reyesIngest,
    gapFindings: [
      {
        severity: "high",
        text: "No record of any independent verification between drafting the March 1 affirmation and filing — the corpus contains ChatGPT prompt logs but no Westlaw/Lexis search history. Schwartz testified Fastcase had lapsed via a firm billing error.",
      },
      {
        severity: "medium",
        text: "Internal Levidow communications about how to respond to the May 4 Order to Show Cause are not in the public docket and would be candidates for privilege review in a complete ingest.",
      },
      {
        severity: "low",
        text: "Correspondence with the firm's malpractice carrier regarding notice of the sanctions exposure not present in the production.",
      },
    ],
  },
  {
    id: "reyes-northwind",
    name: "Reyes v. Northwind Logistics",
    client: "Maria Reyes",
    matterType: "Employment — Wrongful Termination",
    leadAttorney: "D. Okafor",
    status: "In Review",
    pages: 84213,
    docs: 11920,
    ingestPercent: 100,
    lastActivity: "12 min ago",
    caseTheory: {
      posture:
        "Plaintiff Maria Reyes alleges wrongful termination in retaliation for reporting wage-and-hour violations. Defendant Northwind asserts termination was for documented performance issues.",
      claims: [
        "Retaliatory discharge (Labor Code 1102.5)",
        "Failure to pay overtime",
        "Wrongful termination in violation of public policy",
      ],
      defenses: [
        "Legitimate, non-retaliatory business reason",
        "Performance documentation predates protected activity",
      ],
      keyDates: [
        { label: "Reyes hired", date: "2019-04-08" },
        { label: "First wage complaint (internal)", date: "2021-02-11" },
        { label: "Negative performance review", date: "2021-02-26" },
        { label: "Termination", date: "2021-03-15" },
      ],
    },
    ingestStages: reyesIngest,
    gapFindings: [
      {
        severity: "high",
        text: "No documents from Reyes's direct supervisor (T. Brandt) between 2021-02-12 and 2021-02-26 — gap around the review's origin.",
      },
      {
        severity: "medium",
        text: "Payroll records referenced in NW-000847 attachments not present in the production. Consider a follow-up RFP.",
      },
      {
        severity: "low",
        text: "3 text messages reference an off-system call on 2021-03-10; no recording or notes in corpus.",
      },
    ],
  },
  {
    id: "atlas-merger",
    name: "Atlas Foods — Acquisition Diligence",
    client: "Atlas Foods Inc.",
    matterType: "Commercial — M&A Diligence",
    leadAttorney: "P. Lindqvist",
    status: "Ingesting",
    pages: 142655,
    docs: 20431,
    ingestPercent: 72,
    lastActivity: "3 hours ago",
    caseTheory: {
      posture:
        "Buy-side diligence on the acquisition of Atlas Foods. Reviewing material contracts, change-of-control provisions, and outstanding litigation.",
      claims: [],
      defenses: [],
      keyDates: [{ label: "LOI signed", date: "2026-03-02" }],
    },
    ingestStages: [
      { label: "Upload", done: true },
      { label: "OCR (Azure DI)", done: true },
      { label: "Bates stamp", done: true },
      { label: "Dedup + threading", done: false },
      { label: "Extraction", done: false },
      { label: "Privilege scan", done: false },
    ],
    gapFindings: [],
  },
  {
    id: "harbor-injury",
    name: "Calloway v. Harbor Freight Co.",
    client: "James Calloway",
    matterType: "Personal Injury — Premises",
    leadAttorney: "D. Okafor",
    status: "Ready",
    pages: 9788,
    docs: 1342,
    ingestPercent: 100,
    lastActivity: "Yesterday",
    caseTheory: {
      posture:
        "Plaintiff slipped on an unmarked wet floor in a Harbor Freight warehouse. Liability turns on notice of the hazard and adequacy of warnings.",
      claims: ["Negligence", "Premises liability"],
      defenses: ["No actual or constructive notice", "Comparative fault"],
      keyDates: [
        { label: "Incident", date: "2024-08-19" },
        { label: "Incident report filed", date: "2024-08-19" },
      ],
    },
    ingestStages: reyesIngest,
    gapFindings: [
      {
        severity: "medium",
        text: "Maintenance logs for the 24 hours before the incident are missing from the production.",
      },
    ],
  },
];

export const documents: Record<string, SeedDoc[]> = {
  "reyes-northwind": [
    {
      id: "d1",
      bates: "NW-000847",
      title: "RE: Overtime hours — payroll discrepancy",
      type: "Email",
      date: "2021-02-11",
      author: "Maria Reyes",
      recipients: ["Greg Hollis (HR)", "Dana Wu (Payroll)"],
      summary:
        "Reyes reports unpaid overtime for the warehouse night shift and asks HR to correct payroll. First documented internal wage complaint in the corpus.",
      entities: ["Maria Reyes", "Greg Hollis", "Dana Wu"],
      privilege: "none",
      hot: true,
      threadId: "t-ot",
      threadPos: 1,
      threadLen: 5,
      ocrConfidence: "high",
      body:
        "Hi Greg, following up on the night-shift hours from January. Several of us logged overtime that isn't showing on our stubs. Can payroll review and correct? I've attached the shift logs.",
      sortOrder: 1,
    },
    {
      id: "d2",
      bates: "NW-000851",
      title: "RE: Overtime hours — payroll discrepancy",
      type: "Email",
      date: "2021-02-12",
      author: "Greg Hollis (HR)",
      recipients: ["Maria Reyes"],
      summary:
        "HR acknowledges the complaint and says it will be 'looked into.' Establishes employer knowledge of the wage complaint.",
      entities: ["Greg Hollis", "Maria Reyes"],
      privilege: "none",
      hot: true,
      threadId: "t-ot",
      threadPos: 2,
      threadLen: 5,
      ocrConfidence: "high",
      body:
        "Maria — thanks, we'll look into it. Please don't circulate the shift logs more widely while we review.",
      sortOrder: 2,
    },
    {
      id: "d3",
      bates: "NW-001120",
      title: "Performance Review — M. Reyes (Q1)",
      type: "Report",
      date: "2021-02-26",
      author: "Tom Brandt (Ops Mgr)",
      recipients: ["HR File"],
      summary:
        "Negative performance review dated 15 days after Reyes's wage complaint. Cites 'attitude' and 'team friction' with no prior documentation in the file.",
      entities: ["Tom Brandt", "Maria Reyes"],
      privilege: "none",
      hot: true,
      duplicates: 2,
      ocrConfidence: "medium",
      body:
        "Overall rating: Below Expectations. Notes: friction with team, attitude concerns raised this quarter. Recommend performance plan.",
      sortOrder: 3,
    },
    {
      id: "d4",
      bates: "NW-001498",
      title: "Memo to file re: Reyes separation",
      type: "Memo",
      date: "2021-03-12",
      author: "Tom Brandt (Ops Mgr)",
      recipients: ["Greg Hollis (HR)"],
      summary:
        "Internal memo discussing the decision to terminate. References 'the complaint situation' — potentially probative of retaliatory motive.",
      entities: ["Tom Brandt", "Greg Hollis", "Maria Reyes"],
      privilege: "flagged",
      privilegeBasis: "Possible attorney-client — copies in-house counsel L. Stein",
      hot: true,
      ocrConfidence: "high",
      body:
        "Per our discussion, given the complaint situation and ongoing friction, proceeding with separation on the 15th. Looping in Linda for the wording.",
      sortOrder: 4,
    },
    {
      id: "d5",
      bates: "NW-001502",
      title: "Termination letter — M. Reyes",
      type: "Letter",
      date: "2021-03-15",
      author: "Greg Hollis (HR)",
      recipients: ["Maria Reyes"],
      summary: "Formal termination letter citing 'performance.' Dated 32 days after the wage complaint.",
      entities: ["Greg Hollis", "Maria Reyes"],
      privilege: "none",
      hot: false,
      ocrConfidence: "high",
      body:
        "Dear Ms. Reyes, your employment with Northwind Logistics is terminated effective today due to performance. Final pay enclosed.",
      sortOrder: 5,
    },
    {
      id: "d6",
      bates: "NW-002310",
      title: "Counsel guidance on separation wording",
      type: "Email",
      date: "2021-03-13",
      author: "Linda Stein (In-house Counsel)",
      recipients: ["Greg Hollis (HR)", "Tom Brandt"],
      summary:
        "In-house counsel advises on documentation and letter wording. Strong privilege candidate — withhold pending review.",
      entities: ["Linda Stein", "Greg Hollis", "Tom Brandt"],
      privilege: "flagged",
      privilegeBasis: "Attorney-client privilege — legal advice from in-house counsel",
      hot: false,
      ocrConfidence: "high",
      body: "[Flagged for privilege review — body withheld from non-privileged workspace]",
      sortOrder: 6,
    },
  ],
  "harbor-injury": [
    {
      id: "h1",
      bates: "HF-000043",
      title: "Incident report — aisle 7 slip",
      type: "Report",
      date: "2024-08-19",
      author: "Store Manager",
      recipients: ["Risk Mgmt"],
      summary:
        "Contemporaneous incident report describing a wet floor in aisle 7 and the plaintiff's fall. No mention of a warning sign.",
      entities: ["James Calloway"],
      privilege: "none",
      hot: true,
      ocrConfidence: "high",
      body: "Customer slipped near aisle 7 endcap. Floor was wet. Customer transported for evaluation.",
      sortOrder: 1,
    },
    {
      id: "h2",
      bates: "HF-000110",
      title: "Counsel intake notes",
      type: "Memo",
      date: "2024-08-26",
      author: "Outside Counsel",
      recipients: ["File"],
      summary: "Counsel's intake assessment of the claim. Likely work product.",
      entities: ["James Calloway"],
      privilege: "flagged",
      privilegeBasis: "Attorney work product — counsel's mental impressions",
      hot: false,
      ocrConfidence: "high",
      body: "[Flagged for privilege review — body withheld from non-privileged workspace]",
      sortOrder: 2,
    },
  ],
  "atlas-merger": [],
  "mata-avianca": [
    {
      id: "m1",
      bates: "MATA-000001",
      title: "Verified Complaint",
      type: "Letter",
      date: "2022-02-02",
      author: "P. LoDuca (Levidow Levidow & Oberman, P.C.)",
      recipients: ["NY Sup. Ct., New York County"],
      summary:
        "Personal-injury complaint alleging that a metal serving cart struck plaintiff's left knee on Avianca Flight 670 (San Salvador → JFK) on Aug 27, 2019. Filed in state court; Index No. 151004/2022.",
      entities: ["Roberto Mata", "Peter LoDuca", "Avianca Inc."],
      privilege: "none",
      hot: false,
      ocrConfidence: "high",
      body:
        "On or about August 27, 2019, plaintiff Roberto Mata was a passenger on Avianca Flight 670 from San Salvador, El Salvador, to John F. Kennedy International Airport. During the flight, a metal serving cart operated by Avianca personnel struck plaintiff's left knee, causing personal injury. Plaintiff seeks damages under the Montreal Convention.",
      sortOrder: 1,
    },
    {
      id: "m2",
      bates: "MATA-000002",
      title: "Notice of Removal to S.D.N.Y.",
      type: "Letter",
      date: "2022-02-22",
      author: "Condon & Forsyth LLP for Avianca Inc.",
      recipients: ["S.D.N.Y. Clerk", "P. LoDuca"],
      summary:
        "Avianca removes the action to S.D.N.Y. as Case No. 1:22-cv-01461, asserting federal-question jurisdiction under the Montreal Convention.",
      entities: ["Avianca Inc.", "Bartholomew J. Banino"],
      privilege: "none",
      hot: false,
      ocrConfidence: "high",
      body:
        "Defendant Avianca, Inc. respectfully removes this action from the Supreme Court of the State of New York, County of New York, to the United States District Court for the Southern District of New York pursuant to 28 U.S.C. §§ 1331, 1441, and 1446. Plaintiff's claims arise under the Convention for the Unification of Certain Rules for International Carriage by Air (the Montreal Convention).",
      sortOrder: 2,
    },
    {
      id: "m3",
      bates: "MATA-000003",
      title: "Notice of Appearance — P. LoDuca",
      type: "Letter",
      date: "2022-03-31",
      author: "Peter LoDuca",
      recipients: ["S.D.N.Y. Clerk"],
      summary:
        "LoDuca appears for plaintiff in S.D.N.Y. (Schwartz, who drafts the substantive work, is not admitted to practice in S.D.N.Y. and remains in the background).",
      entities: ["Peter LoDuca", "Steven A. Schwartz"],
      privilege: "none",
      hot: false,
      ocrConfidence: "high",
      body:
        "PLEASE TAKE NOTICE that the undersigned, Peter LoDuca, of Levidow, Levidow & Oberman, P.C., hereby appears as counsel of record for plaintiff Roberto Mata in the above-captioned matter.",
      sortOrder: 3,
    },
    {
      id: "m4",
      bates: "MATA-000004",
      title: "Motion to Dismiss — Montreal Convention SoL",
      type: "Memo",
      date: "2023-01-13",
      author: "Condon & Forsyth LLP for Avianca Inc.",
      recipients: ["Hon. P. Kevin Castel"],
      summary:
        "Avianca moves to dismiss as time-barred under Article 35 of the Montreal Convention (two-year condition precedent; not subject to equitable tolling).",
      entities: ["Avianca Inc.", "Bartholomew J. Banino", "Marissa N. Lefland"],
      privilege: "none",
      hot: false,
      ocrConfidence: "high",
      body:
        "Plaintiff's claim must be dismissed because it was not brought within two years of the date the aircraft arrived at its destination, as required by Article 35 of the Montreal Convention. Article 35 imposes a condition precedent to the right of action that is not subject to equitable tolling.",
      sortOrder: 4,
    },
    {
      id: "m5",
      bates: "MATA-000005",
      title: "Affirmation in Opposition to Motion to Dismiss",
      type: "Memo",
      date: "2023-03-01",
      author: "P. LoDuca (drafted by S. Schwartz)",
      recipients: ["Hon. P. Kevin Castel"],
      summary:
        "THE INFAMOUS FILING. Cites six judicial decisions — none of which exist — to argue that Avianca's Chapter 11 stay tolled the Montreal Convention's two-year limitations period. All six were ChatGPT fabrications.",
      entities: ["Peter LoDuca", "Steven A. Schwartz", "ChatGPT"],
      privilege: "none",
      hot: true,
      ocrConfidence: "high",
      body:
        "Plaintiff respectfully submits that the Court should deny defendant's motion. As held in Varghese v. China Southern Airlines Co. Ltd., 925 F.3d 1339 (11th Cir. 2019), the Montreal Convention's two-year period is tolled during a defendant's bankruptcy stay. See also Shaboon v. EgyptAir, 2013 IL App (1st) 111279-U; Petersen v. Iran Air, 905 F. Supp. 2d 121 (D.D.C. 2012); Martinez v. Delta Airlines, Inc., 2019 WL 4639462 (Tex. App. Sept. 25, 2019); Estate of Durden v. KLM Royal Dutch Airlines, 2017 WL 2418825 (Ga. Ct. App. June 5, 2017); Miller v. United Airlines, Inc., 174 F.3d 366 (2d Cir. 1999).",
      sortOrder: 5,
    },
    {
      id: "m6",
      bates: "MATA-000006",
      title: "Reply Memorandum re: Motion to Dismiss",
      type: "Memo",
      date: "2023-03-15",
      author: "Condon & Forsyth LLP for Avianca Inc.",
      recipients: ["Hon. P. Kevin Castel", "P. LoDuca"],
      summary:
        "Avianca's reply notes that counsel was 'unable to locate most of the case law cited in plaintiff's opposition' and lists seven non-existent decisions in quotation marks.",
      entities: ["Avianca Inc.", "Bartholomew J. Banino"],
      privilege: "none",
      hot: true,
      ocrConfidence: "high",
      body:
        "Defendant has been unable to locate most of the case law cited in plaintiff's Affirmation in Opposition. The following purported decisions do not appear in any reporter or database known to counsel: 'Varghese v. China Southern Airlines Co. Ltd., 925 F.3d 1339 (11th Cir. 2019)'; 'Shaboon v. EgyptAir'; 'Petersen v. Iran Air'; 'Martinez v. Delta Airlines, Inc.'; 'Estate of Durden v. KLM Royal Dutch Airlines'; 'Miller v. United Airlines, Inc.'",
      sortOrder: 6,
    },
    {
      id: "m7",
      bates: "MATA-000007",
      title: "Order to Produce Cited Decisions",
      type: "Letter",
      date: "2023-04-11",
      author: "Hon. P. Kevin Castel",
      recipients: ["P. LoDuca"],
      summary:
        "Court orders LoDuca to file copies of the eight cited decisions by April 18 (later extended to April 25) or face dismissal under Rule 41(b).",
      entities: ["P. Kevin Castel", "Peter LoDuca"],
      privilege: "none",
      hot: false,
      ocrConfidence: "high",
      body:
        "Plaintiff's counsel shall file an affidavit attaching copies of the eight cited decisions referenced in his Affirmation in Opposition no later than April 18, 2023. Failure to comply will result in dismissal under Federal Rule of Civil Procedure 41(b).",
      sortOrder: 7,
    },
    {
      id: "m8",
      bates: "MATA-000008",
      title: "Affidavit Attaching Cited Decisions (with ChatGPT transcripts)",
      type: "Memo",
      date: "2023-04-25",
      author: "P. LoDuca (drafted by S. Schwartz)",
      recipients: ["Hon. P. Kevin Castel"],
      summary:
        "Files purported 'excerpts' of the fabricated opinions (themselves ChatGPT-generated) and attaches the ChatGPT prompt/response screenshots as exhibits. Concedes Zicherman 'could not be located.'",
      entities: ["Peter LoDuca", "Steven A. Schwartz", "ChatGPT"],
      privilege: "none",
      hot: true,
      ocrConfidence: "high",
      body:
        "Annexed hereto as Exhibits A through G are excerpts of the cited decisions. With respect to Zicherman v. Korean Air Lines Co., 516 F.3d 1237 (11th Cir. 2008), affiant has been unable to locate the decision. Exhibit H attaches the ChatGPT prompt and response history reflecting the research conducted.",
      sortOrder: 8,
    },
    {
      id: "m9",
      bates: "MATA-000009",
      title: "Order to Show Cause re: Sanctions",
      type: "Letter",
      date: "2023-05-04",
      author: "Hon. P. Kevin Castel",
      recipients: ["P. LoDuca", "S. Schwartz", "Levidow, Levidow & Oberman, P.C."],
      summary:
        "Castel orders LoDuca, Schwartz, and the firm to show cause why they should not be sanctioned under Rule 11, 28 U.S.C. § 1927, and the court's inherent authority. Sets June 8 hearing.",
      entities: ["P. Kevin Castel", "Peter LoDuca", "Steven A. Schwartz"],
      privilege: "none",
      hot: true,
      ocrConfidence: "high",
      body:
        "It is hereby ORDERED that Peter LoDuca, Steven A. Schwartz, and Levidow, Levidow & Oberman, P.C., shall appear before this Court on June 8, 2023, to show cause why they should not be sanctioned pursuant to Federal Rule of Civil Procedure 11(b)(2), (c), 28 U.S.C. § 1927, and the inherent power of the Court for the submission of judicial opinions that do not exist.",
      sortOrder: 9,
    },
    {
      id: "m10",
      bates: "MATA-000010",
      title: "Schwartz Declaration in Response to OSC",
      type: "Memo",
      date: "2023-05-25",
      author: "Steven A. Schwartz",
      recipients: ["Hon. P. Kevin Castel"],
      summary:
        "First written admission that ChatGPT generated the cited cases. Attaches smartphone screenshots of Schwartz's ChatGPT exchange, including his prompt 'Is varghese a real case' and the bot's reassurance that it was.",
      entities: ["Steven A. Schwartz", "ChatGPT"],
      privilege: "none",
      hot: true,
      ocrConfidence: "high",
      body:
        "I deeply regret using ChatGPT in conducting legal research. I was operating under the misconception that ChatGPT was a reliable search engine. I did not understand that ChatGPT could fabricate cases. I attach as Exhibit A screenshots of my chat exchanges, including my inquiry 'Is varghese a real case,' to which ChatGPT responded affirmatively and provided a fabricated citation to the Federal Reporter.",
      sortOrder: 10,
    },
    {
      id: "m11",
      bates: "MATA-000011",
      title: "Supplemental Declarations — Contrition & Remedial Measures",
      type: "Memo",
      date: "2023-06-06",
      author: "S. Schwartz; P. LoDuca; T. Corvino (Levidow partner)",
      recipients: ["Hon. P. Kevin Castel"],
      summary:
        "Pre-hearing declarations expressing remorse. Corvino's portion describes remedial CLE the firm has implemented and references guidance received from outside ethics counsel.",
      entities: ["Steven A. Schwartz", "Peter LoDuca", "Thomas Corvino"],
      privilege: "flagged",
      privilegeBasis:
        "Corvino's portion references guidance from outside ethics counsel; portions may be attorney-client / work-product privileged.",
      hot: false,
      ocrConfidence: "high",
      body:
        "[Flagged for privilege review — body withheld from non-privileged workspace pending decision on the ethics-counsel guidance referenced in paragraphs 8–12.]",
      sortOrder: 11,
    },
    {
      id: "m12",
      bates: "MATA-000012",
      title: "Opinion & Order on Sanctions (678 F. Supp. 3d 443)",
      type: "Report",
      date: "2023-06-22",
      author: "Hon. P. Kevin Castel",
      recipients: ["All counsel"],
      summary:
        "Imposes $5,000 joint-and-several Rule 11 sanction against Schwartz, LoDuca, and Levidow. Finds 'subjective bad faith' arising from the attorneys' continued defense of the fakes after Avianca's March 15 challenge.",
      entities: ["P. Kevin Castel", "Peter LoDuca", "Steven A. Schwartz"],
      privilege: "none",
      hot: true,
      ocrConfidence: "high",
      body:
        "Technological advances are commonplace and there is nothing inherently improper about using a reliable artificial intelligence tool for assistance. But existing rules impose a gatekeeping role on attorneys to ensure the accuracy of their filings. Peter LoDuca, Steven A. Schwartz and the law firm of Levidow, Levidow & Oberman P.C. abandoned their responsibilities when they submitted non-existent judicial opinions with fake quotes and citations created by the artificial intelligence tool ChatGPT, then continued to stand by the fake opinions after judicial orders called their existence into question. The Varghese decision shows stylistic and reasoning flaws that do not generally appear in decisions issued by United States Courts of Appeals. Its legal analysis is gibberish. Respondents are ordered, jointly and severally, to pay a penalty of $5,000 into the Registry of the Court.",
      sortOrder: 12,
    },
    {
      id: "m13",
      bates: "MATA-000013",
      title: "Order Granting Motion to Dismiss (time-barred)",
      type: "Letter",
      date: "2023-06-22",
      author: "Hon. P. Kevin Castel",
      recipients: ["All counsel"],
      summary:
        "Separately dismisses the underlying personal-injury claim with prejudice as time-barred under Article 35 of the Montreal Convention.",
      entities: ["P. Kevin Castel", "Avianca Inc."],
      privilege: "none",
      hot: false,
      ocrConfidence: "high",
      body:
        "Defendant's motion to dismiss is GRANTED. Plaintiff's claim is barred by the Montreal Convention's two-year limitations period, which is a condition precedent to the right of action and is not subject to equitable tolling.",
      sortOrder: 13,
    },
  ],
};

export const chronologyEvents: Record<
  string,
  { id: string; date: string; description: string; bates: string; page: number; confidence: ChronEvent["confidence"]; accepted: boolean | null; issueTags: string[] }[]
> = {
  "reyes-northwind": [
    {
      id: "c1",
      date: "2019-04-08",
      description: "Maria Reyes hired as warehouse shift lead at Northwind Logistics.",
      bates: "NW-000847",
      page: 1,
      confidence: "high",
      accepted: true,
      issueTags: ["Background"],
    },
    {
      id: "c2",
      date: "2021-02-11",
      description: "Reyes submits internal complaint about unpaid overtime to HR (Greg Hollis).",
      bates: "NW-000847",
      page: 1,
      confidence: "high",
      accepted: true,
      issueTags: ["Protected Activity", "Wage Claim"],
    },
    {
      id: "c3",
      date: "2021-02-12",
      description: "HR acknowledges the complaint in writing.",
      bates: "NW-000851",
      page: 1,
      confidence: "high",
      accepted: true,
      issueTags: ["Employer Knowledge"],
    },
    {
      id: "c4",
      date: "2021-02-26",
      description: "First negative performance review of Reyes, 15 days after the complaint.",
      bates: "NW-001120",
      page: 1,
      confidence: "high",
      accepted: null,
      issueTags: ["Pretext", "Causation"],
    },
    {
      id: "c5",
      date: "2021-03-12",
      description: "Ops manager memo references 'the complaint situation' while planning separation.",
      bates: "NW-001498",
      page: 1,
      confidence: "medium",
      accepted: null,
      issueTags: ["Retaliatory Motive"],
    },
    {
      id: "c6",
      date: "2021-03-15",
      description: "Reyes terminated; letter cites performance.",
      bates: "NW-001502",
      page: 1,
      confidence: "high",
      accepted: null,
      issueTags: ["Adverse Action"],
    },
  ],
  "harbor-injury": [
    {
      id: "hc1",
      date: "2024-08-19",
      description: "Plaintiff slips on wet floor in aisle 7; incident report filed same day.",
      bates: "HF-000043",
      page: 1,
      confidence: "high",
      accepted: true,
      issueTags: ["Incident", "Notice"],
    },
  ],
  "atlas-merger": [],
  "mata-avianca": [
    {
      id: "mc1",
      date: "2019-08-27",
      description: "Roberto Mata injured on Avianca Flight 670 (San Salvador → JFK) when a metal serving cart struck his left knee.",
      bates: "MATA-000001",
      page: 1,
      confidence: "high",
      accepted: true,
      issueTags: ["Incident", "Notice"],
    },
    {
      id: "mc2",
      date: "2022-02-02",
      description: "Verified Complaint filed in NY Supreme Court (Index No. 151004/2022).",
      bates: "MATA-000001",
      page: 1,
      confidence: "high",
      accepted: true,
      issueTags: ["Procedural"],
    },
    {
      id: "mc3",
      date: "2022-02-22",
      description: "Avianca removes to S.D.N.Y. (Case No. 1:22-cv-01461), asserting Montreal Convention federal-question jurisdiction.",
      bates: "MATA-000002",
      page: 1,
      confidence: "high",
      accepted: true,
      issueTags: ["Procedural"],
    },
    {
      id: "mc4",
      date: "2023-01-13",
      description: "Avianca moves to dismiss as time-barred under Article 35 of the Montreal Convention.",
      bates: "MATA-000004",
      page: 1,
      confidence: "high",
      accepted: true,
      issueTags: ["Statute of Limitations", "Defense"],
    },
    {
      id: "mc5",
      date: "2023-03-01",
      description: "Plaintiff's Affirmation in Opposition cites six judicial decisions — all ChatGPT fabrications.",
      bates: "MATA-000005",
      page: 1,
      confidence: "high",
      accepted: true,
      issueTags: ["Sanctions Conduct", "Rule 11"],
    },
    {
      id: "mc6",
      date: "2023-03-15",
      description: "Avianca's Reply notes counsel was 'unable to locate most of the case law cited.'",
      bates: "MATA-000006",
      page: 1,
      confidence: "high",
      accepted: true,
      issueTags: ["Sanctions Conduct", "Notice"],
    },
    {
      id: "mc7",
      date: "2023-04-25",
      description: "LoDuca affidavit attaches fabricated 'excerpts' of the fake cases plus ChatGPT prompt-and-response screenshots.",
      bates: "MATA-000008",
      page: 1,
      confidence: "high",
      accepted: true,
      issueTags: ["Sanctions Conduct", "Bad Faith"],
    },
    {
      id: "mc8",
      date: "2023-05-04",
      description: "Castel issues Order to Show Cause re: sanctions under Rule 11, § 1927, and inherent authority.",
      bates: "MATA-000009",
      page: 1,
      confidence: "high",
      accepted: true,
      issueTags: ["Sanctions Conduct"],
    },
    {
      id: "mc9",
      date: "2023-06-08",
      description: "Sanctions hearing — sworn testimony from LoDuca and Schwartz; prepared statements of remorse.",
      bates: "MATA-000010",
      page: 1,
      confidence: "high",
      accepted: true,
      issueTags: ["Sanctions Conduct"],
    },
    {
      id: "mc10",
      date: "2023-06-22",
      description: "Castel imposes $5,000 joint-and-several Rule 11 sanction; separately dismisses underlying claim as time-barred.",
      bates: "MATA-000012",
      page: 1,
      confidence: "high",
      accepted: true,
      issueTags: ["Sanctions Conduct", "Adverse Action"],
    },
  ],
};

export const entityRecords: Record<string, Entity[]> = {
  "reyes-northwind": [
    {
      id: "e1",
      name: "Maria Reyes",
      role: "Plaintiff / Warehouse Shift Lead",
      org: "Northwind Logistics",
      aliases: ["M. Reyes", "Maria R."],
      mentions: 1842,
      firstSeen: "NW-000012",
      relationships: [
        { name: "Greg Hollis", relation: "Reported wage complaint to" },
        { name: "Tom Brandt", relation: "Direct report to" },
      ],
    },
    {
      id: "e2",
      name: "Tom Brandt",
      role: "Operations Manager",
      org: "Northwind Logistics",
      aliases: ["T. Brandt", "Thomas Brandt"],
      mentions: 612,
      firstSeen: "NW-000204",
      relationships: [
        { name: "Maria Reyes", relation: "Supervised" },
        { name: "Linda Stein", relation: "Consulted re: separation" },
      ],
    },
    {
      id: "e3",
      name: "Greg Hollis",
      role: "HR Generalist",
      org: "Northwind Logistics",
      aliases: ["G. Hollis"],
      mentions: 487,
      firstSeen: "NW-000301",
      relationships: [
        { name: "Maria Reyes", relation: "Received complaint from" },
        { name: "Linda Stein", relation: "Escalated to" },
      ],
    },
    {
      id: "e4",
      name: "Linda Stein",
      role: "In-house Counsel",
      org: "Northwind Logistics",
      aliases: ["L. Stein", "Linda S."],
      mentions: 96,
      firstSeen: "NW-002310",
      relationships: [
        { name: "Tom Brandt", relation: "Advised" },
        { name: "Greg Hollis", relation: "Advised" },
      ],
    },
  ],
  "harbor-injury": [
    {
      id: "he1",
      name: "James Calloway",
      role: "Plaintiff",
      org: "—",
      aliases: ["J. Calloway"],
      mentions: 211,
      firstSeen: "HF-000043",
      relationships: [],
    },
  ],
  "atlas-merger": [],
  "mata-avianca": [
    {
      id: "me1",
      name: "Steven A. Schwartz",
      role: "Research Counsel (not S.D.N.Y.-admitted)",
      org: "Levidow, Levidow & Oberman, P.C.",
      aliases: ["S. Schwartz", "Steven Schwartz"],
      mentions: 487,
      firstSeen: "MATA-000005",
      relationships: [
        { name: "Peter LoDuca", relation: "Drafted brief filed by" },
        { name: "ChatGPT", relation: "Used for research" },
      ],
    },
    {
      id: "me2",
      name: "Peter LoDuca",
      role: "Attorney of Record",
      org: "Levidow, Levidow & Oberman, P.C.",
      aliases: ["P. LoDuca"],
      mentions: 412,
      firstSeen: "MATA-000003",
      relationships: [
        { name: "Steven A. Schwartz", relation: "Filed work drafted by" },
        { name: "P. Kevin Castel", relation: "Sanctioned by" },
      ],
    },
    {
      id: "me3",
      name: "P. Kevin Castel",
      role: "Senior U.S. District Judge, S.D.N.Y.",
      org: "United States District Court",
      aliases: ["Hon. Castel", "Judge Castel"],
      mentions: 318,
      firstSeen: "MATA-000007",
      relationships: [
        { name: "Peter LoDuca", relation: "Issued sanctions against" },
        { name: "Steven A. Schwartz", relation: "Issued sanctions against" },
      ],
    },
    {
      id: "me4",
      name: "Roberto Mata",
      role: "Plaintiff / Passenger",
      org: "—",
      aliases: ["R. Mata"],
      mentions: 96,
      firstSeen: "MATA-000001",
      relationships: [{ name: "Peter LoDuca", relation: "Represented by" }],
    },
    {
      id: "me5",
      name: "Bartholomew J. Banino",
      role: "Defense Counsel",
      org: "Condon & Forsyth LLP",
      aliases: ["B. Banino"],
      mentions: 84,
      firstSeen: "MATA-000002",
      relationships: [{ name: "Avianca Inc.", relation: "Represented" }],
    },
    {
      id: "me6",
      name: "Thomas Corvino",
      role: "Partner",
      org: "Levidow, Levidow & Oberman, P.C.",
      aliases: ["T. Corvino"],
      mentions: 21,
      firstSeen: "MATA-000011",
      relationships: [
        { name: "Steven A. Schwartz", relation: "Firm partner of" },
        { name: "Peter LoDuca", relation: "Firm partner of" },
      ],
    },
    {
      id: "me7",
      name: "ChatGPT",
      role: "AI Tool (cited as 'research source')",
      org: "OpenAI",
      aliases: ["GPT", "ChatGPT-3.5"],
      mentions: 142,
      firstSeen: "MATA-000005",
      relationships: [{ name: "Steven A. Schwartz", relation: "Queried by" }],
    },
  ],
};

export const seedChat: Record<string, { id: string; role: "user" | "themis"; text: string; bates?: { bates: string; page: number }[]; confidence?: ChronEvent["confidence"] }[]> = {
  "mata-avianca": [
    {
      id: "mq1",
      role: "user",
      text: "What's the timeline between the fabricated affirmation and the sanctions order?",
    },
    {
      id: "ma1",
      role: "themis",
      text:
        "113 days. The Affirmation in Opposition citing six ChatGPT-fabricated cases (Varghese, Shaboon, Petersen, Martinez, Durden, Miller) was filed 2023-03-01. Avianca's reply 14 days later (2023-03-15) flagged that counsel was 'unable to locate most of the case law cited.' Judge Castel's Order to Show Cause issued 2023-05-04 (64 days in); the sanctions hearing was held 2023-06-08 (99 days). The $5,000 joint-and-several Rule 11 sanction issued 2023-06-22 (113 days from the offending brief). Castel found 'subjective bad faith' arising from the attorneys' continued defense of the fakes after Avianca's March 15 challenge.",
      confidence: "high",
      bates: [
        { bates: "MATA-000005", page: 1 },
        { bates: "MATA-000006", page: 1 },
        { bates: "MATA-000009", page: 1 },
        { bates: "MATA-000012", page: 1 },
      ],
    },
  ],
  "reyes-northwind": [
    {
      id: "q1",
      role: "user",
      text: "How much time passed between Reyes's wage complaint and her termination? What's our best evidence for retaliation?",
    },
    {
      id: "a1",
      role: "themis",
      text:
        "32 days passed between the documented wage complaint (NW-000847, 2021-02-11) and the termination letter (NW-001502, 2021-03-15). The strongest evidence for retaliation is the temporal sequence plus the Brandt memo to file (NW-001498) which references 'the complaint situation' while discussing separation — 14 days before the termination. The first negative review of Reyes (NW-001120) lands exactly 15 days after the complaint, with no prior negative documentation in her file. Every citation below is verified against its source page.",
      confidence: "high",
      bates: [
        { bates: "NW-000847", page: 1 },
        { bates: "NW-001120", page: 1 },
        { bates: "NW-001498", page: 1 },
        { bates: "NW-001502", page: 1 },
      ],
    },
  ],
};
