// Client-side PDF exports — Sprint 2 stub. Server-side rendering (Puppeteer,
// react-pdf, or DOCX generator) is the longer-term path; jsPDF gets us a
// court-style preview that ships today behind the same lock contract the
// real exports will use.
//
// jsPDF is heavy (~250kb gz with html2canvas/purify). It is dynamically
// imported on first export so the initial bundle stays lean.

import type { jsPDF as JsPDFType } from "jspdf";
import type { Binder, ChronEvent, DocItem, MatterDetail } from "../types";

async function loadJsPdf() {
  const mod = await import("jspdf");
  return mod.jsPDF;
}

interface ExportLock {
  /** Matter must be fully ingested + privilege scan complete before exports. */
  reason: string;
}

export function exportLockForMatter(matter: MatterDetail): ExportLock | null {
  if (matter.ingestPercent < 100) {
    return { reason: `Ingest is ${matter.ingestPercent}% complete. Exports unlock when the corpus finishes processing.` };
  }
  const lastStage = matter.ingestStages[matter.ingestStages.length - 1];
  if (lastStage && !lastStage.done) {
    return { reason: "Privilege scan must complete before exports can include privileged-decided documents." };
  }
  return null;
}

function pdfHeader(doc: JsPDFType, matter: MatterDetail, title: string) {
  doc.setFont("times", "bold");
  doc.setFontSize(18);
  doc.text(title.toUpperCase(), 40, 60);
  doc.setFont("times", "normal");
  doc.setFontSize(11);
  doc.text(matter.name, 40, 80);
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(`Matter ID: ${matter.id}  ·  Generated by Themis  ·  ${new Date().toLocaleString()}`, 40, 96);
  doc.setTextColor(0);
  doc.setLineWidth(0.5);
  doc.line(40, 104, 555, 104);
}

function pdfFooter(doc: JsPDFType, lineCount: number, footer: string) {
  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(140);
    doc.text(footer, 40, 800);
    doc.text(`Page ${i} of ${total}`, 555 - doc.getTextWidth(`Page ${i} of ${total}`), 800);
    doc.setTextColor(0);
  }
  void lineCount;
}

export async function exportChronologyPdf(matter: MatterDetail, events: ChronEvent[]) {
  const Ctor = await loadJsPdf();
  const doc = new Ctor({ unit: "pt", format: "letter" });
  pdfHeader(doc, matter, "Chronology");
  let y = 130;
  doc.setFont("times", "bold");
  doc.setFontSize(10);
  doc.text("Date", 40, y);
  doc.text("Event", 130, y);
  doc.text("Source", 480, y);
  y += 8;
  doc.setLineWidth(0.3);
  doc.line(40, y, 555, y);
  y += 14;
  doc.setFont("times", "normal");
  doc.setFontSize(10);

  const accepted = events.filter((e) => e.accepted === true);
  if (accepted.length === 0) {
    doc.text("No accepted events.", 40, y);
  } else {
    for (const e of accepted) {
      const lines = doc.splitTextToSize(e.description, 340) as string[];
      if (y + lines.length * 12 + 8 > 760) {
        doc.addPage();
        y = 60;
      }
      doc.setFont("times", "normal");
      doc.text(e.date, 40, y);
      doc.text(lines, 130, y);
      doc.setFont("courier", "normal");
      doc.setFontSize(9);
      doc.text(`${e.citation.bates} p.${e.citation.page}`, 480, y);
      doc.setFont("times", "normal");
      doc.setFontSize(10);
      y += lines.length * 12 + 10;
    }
  }

  pdfFooter(
    doc,
    accepted.length,
    "Every citation in this chronology was verified against its source page at export time.",
  );
  doc.save(`${matter.id}-chronology.pdf`);
}

export async function exportPrivilegeLogPdf(matter: MatterDetail, docs: DocItem[]) {
  const Ctor = await loadJsPdf();
  const doc = new Ctor({ unit: "pt", format: "letter" });
  pdfHeader(doc, matter, "Privilege Log");
  let y = 130;
  doc.setFont("times", "bold");
  doc.setFontSize(10);
  doc.text("#", 40, y);
  doc.text("Bates", 70, y);
  doc.text("Date", 140, y);
  doc.text("Type", 195, y);
  doc.text("Author / Recipients", 250, y);
  doc.text("Basis", 410, y);
  doc.text("Decision", 510, y);
  y += 8;
  doc.line(40, y, 555, y);
  y += 14;
  doc.setFont("times", "normal");
  doc.setFontSize(9);

  const decided = docs.filter((d) => d.privilege === "withheld" || d.privilege === "cleared");
  if (decided.length === 0) {
    doc.text("No privilege decisions logged.", 40, y);
  } else {
    decided.forEach((d, i) => {
      if (y > 760) {
        doc.addPage();
        y = 60;
      }
      const basisLines = doc.splitTextToSize(d.privilegeBasis ?? "—", 90) as string[];
      const toLines = doc.splitTextToSize(
        `${d.author}\n${d.recipients.join(", ")}`,
        150,
      ) as string[];
      const lineCount = Math.max(basisLines.length, toLines.length, 1);
      doc.text(String(i + 1), 40, y);
      doc.setFont("courier", "normal");
      doc.text(d.bates, 70, y);
      doc.setFont("times", "normal");
      doc.text(d.date, 140, y);
      doc.text(d.type, 195, y);
      doc.text(toLines, 250, y);
      doc.text(basisLines, 410, y);
      doc.setFont("times", "bold");
      doc.text(d.privilege.toUpperCase(), 510, y);
      doc.setFont("times", "normal");
      y += lineCount * 11 + 8;
    });
  }
  pdfFooter(doc, decided.length, "Privilege log generated per FRCP 26(b)(5)(A).");
  doc.save(`${matter.id}-privilege-log.pdf`);
}

// Word export — HTML-as-.doc. Word opens this natively. Tiny, dep-free, good
// enough for the prototype; a true .docx generator can drop in behind this
// same function signature.
export function exportChronologyDoc(matter: MatterDetail, events: ChronEvent[]) {
  const accepted = events.filter((e) => e.accepted === true);
  const rows = accepted
    .map(
      (e) => `
        <tr>
          <td style="padding:6pt 10pt;border-bottom:0.5pt solid #ccc;font-family:'Times New Roman'">${e.date}</td>
          <td style="padding:6pt 10pt;border-bottom:0.5pt solid #ccc;font-family:'Times New Roman'">${escapeHtml(e.description)}</td>
          <td style="padding:6pt 10pt;border-bottom:0.5pt solid #ccc;font-family:'Courier New';font-size:9pt;white-space:nowrap">${e.citation.bates} p.${e.citation.page}</td>
        </tr>`,
    )
    .join("");
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${escapeHtml(matter.name)} — Chronology</title>
<style>body{font-family:'Times New Roman';margin:1in;color:#000}h1{font-size:18pt;margin:0 0 6pt}p.meta{font-size:9pt;color:#666;margin:0 0 18pt}table{width:100%;border-collapse:collapse;font-size:11pt}th{text-align:left;border-bottom:1pt solid #000;padding:6pt 10pt;font-size:10pt}p.foot{font-size:8pt;color:#666;margin-top:24pt}</style></head>
<body>
<h1>Chronology</h1>
<p class="meta">${escapeHtml(matter.name)} · Matter ID: ${matter.id} · Generated by Themis · ${new Date().toLocaleString()}</p>
<table>
  <thead><tr><th>Date</th><th>Event</th><th>Source</th></tr></thead>
  <tbody>${rows || `<tr><td colspan="3" style="padding:18pt;text-align:center;color:#666">No accepted events.</td></tr>`}</tbody>
</table>
<p class="foot">Every citation in this chronology was verified against its source page at export time.</p>
</body></html>`;

  const blob = new Blob([html], { type: "application/msword" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${matter.id}-chronology.doc`;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (ch) =>
    ch === "&" ? "&amp;" : ch === "<" ? "&lt;" : ch === ">" ? "&gt;" : ch === '"' ? "&quot;" : "&#39;",
  );
}

export async function exportBinderPdf(binder: Binder) {
  const Ctor = await loadJsPdf();
  const doc = new Ctor({ unit: "pt", format: "letter" });
  doc.setFont("times", "bold");
  doc.setFontSize(20);
  doc.text(binder.name, 40, 80);
  doc.setFont("times", "normal");
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(`Exhibit set · ${binder.items.length} item(s) · Themis`, 40, 100);
  doc.setTextColor(0);
  doc.line(40, 110, 555, 110);

  let y = 140;
  doc.setFont("times", "bold");
  doc.setFontSize(10);
  doc.text("#", 40, y);
  doc.text("Label", 80, y);
  doc.text("Bates", 380, y);
  doc.text("Type", 460, y);
  doc.text("Date", 510, y);
  y += 8;
  doc.line(40, y, 555, y);
  y += 14;
  doc.setFont("times", "normal");
  doc.setFontSize(10);

  binder.items.forEach((it, i) => {
    if (y > 760) {
      doc.addPage();
      y = 60;
    }
    const lines = doc.splitTextToSize(it.label, 280) as string[];
    doc.text(String(i + 1).padStart(2, "0"), 40, y);
    doc.text(lines, 80, y);
    doc.setFont("courier", "normal");
    doc.setFontSize(9);
    doc.text(it.bates, 380, y);
    doc.setFont("times", "normal");
    doc.setFontSize(10);
    doc.text(it.type, 460, y);
    doc.text(it.date, 510, y);
    y += lines.length * 12 + 8;
  });
  doc.save(`${binder.name.replace(/\s+/g, "-")}.pdf`);
}
