#!/usr/bin/env python3
"""
UNDERTOW — the sound department, on the command line.

    python3 undertone.py spot  ../../../UNDERTOW-EP1-SCRIPT.md
    python3 undertone.py chart "I'm not afraid of the water." 2.0
    python3 undertone.py lines ../../../UNDERTOW-EP1-SCRIPT.md

`spot` is the one that matters. It turns a teleplay into the machine-readable
cue sheet that everything downstream renders from — the mix, the mouth charts,
the shot prompts, the QC expectations. One source, so they cannot drift apart.

The cue sheet it emits is a DRAFT with the mechanical work done: every spoken
line found, timed by read rate, marked sync-free where the script already says
the speaker is off screen, and given a Fathom tier guessed from the slug line.
The dramatic decisions — which cue, which motif, where the silence goes — are
left blank on purpose. A spotting sheet is a creative document; this only
removes the typing.
"""
import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import dialogue  # noqa: E402
import visemes as V  # noqa: E402

FPS = 24

# Spoken English runs about 150 words a minute in conversation and slower in
# performance, where pauses are doing work. 2.6 words/second is a read rate for
# unhurried delivery; it is only ever a first estimate, and any line that has
# been recorded uses the recording's real length instead.
WORDS_PER_SECOND = 2.6
MIN_LINE_SECONDS = 0.6


def estimate_seconds(text):
    n = len(dialogue.words(text))
    return max(MIN_LINE_SECONDS, n / WORDS_PER_SECOND)


# Slug lines say where a scene is; where a scene is says which room it sounds
# like. This is a first guess, marked as one — "INT. POOL" is sunlit, but a
# scene that goes under mid-way is not, and no regex knows that.
TIER_HINTS = [
    (r"HADAL|TRENCH|THE DEEP\b", "hadal"),
    (r"ABYSS|DROWNED RUIN|SEALED", "abyssal"),
    (r"MIDNIGHT|DEEP WATER|BENEATH", "midnight"),
    (r"UNDERWATER|SUBMERGED|UNDER THE", "twilight"),
    (r"POOL|SEA|WATER|HARBOUR|HARBOR|DOCK|BOAT", "sunlit"),
]


def guess_tier(heading):
    up = (heading or "").upper()
    for pattern, tier in TIER_HINTS:
        if re.search(pattern, up):
            return tier
    return "air"


def nearest_heading(headings, line_no):
    best = None
    for h in headings:
        if h["line_no"] <= line_no:
            best = h
        else:
            break
    return best["heading"] if best else ""


def cmd_spot(args):
    with open(args.script, encoding="utf-8") as fh:
        src = fh.read()
    lines = dialogue.parse(src)
    headings = dialogue.scene_headings(src)

    cues, t = [], 0.0
    for entry in lines:
        heading = nearest_heading(headings, entry["line_no"])
        dur = estimate_seconds(entry["text"])
        cues.append({
            "id": f"{len(cues) + 1:03d}",
            "type": "vo",
            "who": entry["who"],
            "line": entry["text"],
            "direction": entry["direction"],
            "scene": heading,
            "script_line": entry["line_no"],
            # Off-screen lines have no mouth on screen, so they are sync-free
            # before anyone does any work. This is the single cheapest win in
            # the pipeline and it is worth knowing up front rather than
            # discovering it in review.
            "mouth": "visible" if entry["onscreen"] else "offscreen",
            "sync_required": entry["onscreen"],
            "fathom": guess_tier(heading),
            "fathom_confidence": "guessed-from-slug",
            "calm": None,              # a taste call; left for a human
            "cue": None,               # which musical cue, if any
            "at": round(t, 2),         # placeholder ordering, not real timecode
            "estimated_seconds": round(dur, 2),
        })
        t += dur

    onscreen = sum(1 for c in cues if c["sync_required"])
    sheet = {
        "_comment": ("DRAFT cue sheet generated by undertone.py spot. The "
                     "mechanical work is done; the dramatic decisions (cue, "
                     "calm, real timecode) are deliberately left null. `at` is "
                     "running order, NOT timecode — it becomes real when the "
                     "picture exists."),
        "source": os.path.basename(args.script),
        "fps": FPS,
        "counts": {
            "lines": len(cues),
            "sync_required": onscreen,
            "sync_free": len(cues) - onscreen,
            "estimated_dialogue_seconds": round(t, 1),
        },
        "cues": cues,
    }

    out = args.out or os.path.join(
        HERE, "cues-" + re.sub(r"[^A-Za-z0-9]+", "-",
                               os.path.splitext(os.path.basename(args.script))[0]).lower() + ".json")
    with open(out, "w", encoding="utf-8") as fh:
        json.dump(sheet, fh, indent=1, ensure_ascii=False)
        fh.write("\n")

    print(f"  {len(cues)} spoken lines, {t:.0f}s of estimated dialogue")
    print(f"  {onscreen} need lip-sync, {len(cues) - onscreen} are off-screen and free")
    pct = 100.0 * (len(cues) - onscreen) / max(1, len(cues))
    print(f"  {pct:.0f}% sync-free as written — the target is 60%, reachable by "
          f"shot design (see the SOUND BIBLE, Route A)")
    print(f"  wrote {out}")
    return 0


def cmd_chart(args):
    lex = V.load_lexicon()
    pairs = V.transcribe(args.line, lex)
    timeline = V.to_timeline(pairs, args.seconds, lead_s=1.0 / FPS)
    frames = V.chart(timeline, FPS, args.seconds)

    print(f"  {args.line!r}   {args.seconds}s at {FPS}fps")
    print(f"  phones: {' '.join(p for p, _ in pairs)}")
    print()
    for i in range(0, len(frames), 48):
        chunk = frames[i:i + 48]
        print(f"  {i:4d}  {''.join(chunk)}")
    print()
    closures = V.closure_frames(frames)
    print(f"  {len(frames)} frames; lips must be SHUT on {len(closures)} of them: {closures}")
    print("  a missed closure is the one sync error every audience catches")

    if args.out:
        with open(args.out, "w", encoding="utf-8") as fh:
            json.dump({"line": args.line, "seconds": args.seconds, "fps": FPS,
                       "phones": [p for p, _ in pairs], "frames": frames,
                       "closure_frames": closures,
                       "openness": V.openness(frames)}, fh, indent=1)
            fh.write("\n")
        print(f"  wrote {args.out}")
    return 0


def cmd_lines(args):
    with open(args.script, encoding="utf-8") as fh:
        entries = dialogue.parse(fh.read())
    for e in entries:
        tag = "" if e["onscreen"] else f" ({e['suffix']})"
        print(f"  {e['line_no']:5d}  {e['who']}{tag}: {e['text']}")
    print(f"\n  {len(entries)} lines")
    return 0


def main():
    ap = argparse.ArgumentParser(description="UNDERTOW sound department")
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("spot", help="teleplay -> draft cue sheet")
    p.add_argument("script")
    p.add_argument("--out")
    p.set_defaults(fn=cmd_spot)

    p = sub.add_parser("chart", help="line -> per-frame mouth chart")
    p.add_argument("line")
    p.add_argument("seconds", type=float)
    p.add_argument("--out")
    p.set_defaults(fn=cmd_chart)

    p = sub.add_parser("lines", help="list every spoken line in a teleplay")
    p.add_argument("script")
    p.set_defaults(fn=cmd_lines)

    args = ap.parse_args()
    return args.fn(args)


if __name__ == "__main__":
    sys.exit(main())
